import fitz  # PyMuPDF
import pytesseract
from PIL import Image
import io
import os
import structlog
from src.extraction.interfaces import DocumentExtractor

logger = structlog.get_logger()

# Tesseract binary discovery.
# pytesseract calls tesseract.exe via subprocess, so it must be resolvable.
# We check common Windows install locations so it works even if the installer
# didn't add Tesseract to the system PATH.
_TESSERACT_CANDIDATES = [
    os.environ.get("TESSERACT_CMD", ""),
    r"C:\Program Files\Tesseract-OCR\tesseract.exe",
    r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe",
    r"C:\Users\{}\AppData\Local\Programs\Tesseract-OCR\tesseract.exe".format(os.environ.get("USERNAME", "")),
]
for _candidate in _TESSERACT_CANDIDATES:
    if _candidate and os.path.isfile(_candidate):
        pytesseract.pytesseract.tesseract_cmd = _candidate
        logger.info("Resolved Tesseract path", path=_candidate)
        break
else:
    logger.warning("No Tesseract path could be resolved from candidates", candidates=_TESSERACT_CANDIDATES)



def _page_to_text_via_ocr(page: fitz.Page) -> str:
    """
    Renders a PDF page to a high-resolution image and runs Tesseract OCR on it.
    Used as a fallback when the page has no embedded text layer.
    """
    # 2x zoom gives ~144 DPI — good balance between accuracy and speed
    matrix = fitz.Matrix(2.0, 2.0)
    pixmap = page.get_pixmap(matrix=matrix, colorspace=fitz.csRGB)
    img_bytes = pixmap.tobytes("png")
    image = Image.open(io.BytesIO(img_bytes))
    return pytesseract.image_to_string(image, lang="eng")


class PyMuPDFExtractor(DocumentExtractor):
    """
    Extracts text from PDF files using PyMuPDF (fitz).

    Strategy (per page):
      1. Try embedded text extraction via get_text("text") — fast, lossless.
      2. If the page yields no text (e.g. scanned / image-only PDF), fall back
         to rendering the page as a PNG and running Tesseract OCR on it.

    This means the extractor works correctly for both:
      - Native text PDFs  (invoices generated by software)
      - Scanned / image PDFs  (photographed or printed-then-scanned invoices)
    """

    def extract_text(self, file_bytes: bytes) -> str:
        text_content = []
        try:
            with fitz.open(stream=file_bytes, filetype="pdf") as doc:
                for page_num in range(len(doc)):
                    page = doc.load_page(page_num)

                    # --- Primary: embedded text extraction ---
                    text = page.get_text("text").strip()

                    if text:
                        logger.debug(
                            "Text extracted from page",
                            page=page_num + 1,
                            method="embedded",
                            chars=len(text),
                        )
                        text_content.append(text)
                    else:
                        # --- Fallback: OCR ---
                        logger.info(
                            "Page has no embedded text, falling back to OCR",
                            page=page_num + 1,
                        )
                        try:
                            ocr_text = _page_to_text_via_ocr(page).strip()
                            if ocr_text:
                                logger.debug(
                                    "OCR succeeded",
                                    page=page_num + 1,
                                    chars=len(ocr_text),
                                )
                                text_content.append(ocr_text)
                            else:
                                logger.warning(
                                    "OCR returned no text for page",
                                    page=page_num + 1,
                                )
                        except Exception as ocr_err:
                            logger.exception(
                                "OCR failed for page, skipping",
                                page=page_num + 1,
                            )

            return "\n\n".join(text_content)

        except Exception as e:
            raise ValueError(f"Failed to extract text from PDF: {str(e)}")
